# Generated by Django 4.1.4 on 2022-12-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("Ongoing", "Ongoing"),
                    ("Completed", "Completed"),
                ],
                default="Not Started",
                max_length=11,
            ),
        ),
    ]
