# Generated by Django 4.1.4 on 2022-12-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_account_alter_todo_options"),
    ]

    operations = [
        migrations.DeleteModel(name="Account",),
    ]
