# Generated by Django 4.1.4 on 2023-01-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0004_delete_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
